### ISSUE TITLE
Update github actions to use matrix configs

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#104]
See #102 - we want to do the same for the other actions too.

We also need to make sure the path section of the cache step is identical on all. (edit: this is now done in #105)

**Comment by niklasdewally** [comment]
@ozgurakgun now we do all the tests in one file (at the time of writing it was seperated by crate), is there anything else that needs matrixing?

**Comment by ozgurakgun** [comment]
nope, I think this is sorted.
