### ISSUE TITLE
Add global cleaning file

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure-oxide#108]
Would be nice to have some kind of global way of cleaning, including all the dependancies. This could be a `./clean.sh`, which recursively calls a `./clean.sh` for each solver (for example).

Also, do I have to "do something" when the vendored git submodules are updated? Wasn't sure.

This could be done via `git clean --force`, although that has the disadvantage it would nuke files people are editing, not just things that got built.

We could (in principle) even test our clean script cleans, by doing a full build, at the end cleaning, and checking something like `git status --ignored --ignore-submodules=none` comes back clean.

This is useful when some files don't get autorebuilt -- I don't think we want to start doing a full scan of dependancies at every build step, but also if someone does edit a file in one it might be annoying if they can't figure out how to make everything build again.

**Comment by niklasdewally** [comment]
> Also, do I have to "do something" when > the vendored git submodules are 
> updated? Wasn't sure.

I don't think I am sure either - I presume now that we've fixed caching and minion now has a good build time (--quick and so on) we could probably just suggest clean builds for dependencies at certain points?

I am not sure how to communicate to collaborator's "now you need to run clean / do git submodule update".

If we were using crates.io or similar a new version number of minion_rs (for example) would force.a clean build for conjue oxide, but im not sure how that works here.

**Comment by niklasdewally** [comment]
I have a snippet already that can get submodule paths from git (https://github.com/conjure-cp/conjure-oxide/blob/main/etc/ci/get_submodule_paths.sh).

Perhaps something like

1. delete all submodule folders
2. cargo clean
3. git submodule sync
4. cargo build (should do git submodule update --init internally)

would be sufficient
