### ISSUE TITLE
Fix failing CI

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#138]
CI tests went from passing to failing. This doesn't seem to be related to any code changes in any PR.

#136 #137 #135.

**Comment by lixitrixi** [comment]
> Felix found some Mac failures on his local machine.
> 
> However, the failed Ubuntu run cancels the Mac tests, so I cannot see it in CI just yet. Once I fix that (#139), more testing errors might appear....

Turns out the failures were due to mac security and are now fixed for me. I've addressed the Minion errors in #143 but the full test suite doesn't seem to be running for it? Code coverage is also failing but I am unsure how to address that.

**Comment by lixitrixi** [comment]
CI is passing now for #143, and once that's in order we should be able to merge #137 and #141.

**Comment by niklasdewally** [comment]
> the full test suite doesn't seem to be running for it

CI runs tests for minion_rs as well as conjure_oxide, but only does this when the conjure_oxide source changes.  Should probably add minion_rs and the other crates to it as well, or separate out each crate into their own CI tests again.
