### ISSUE TITLE
A failing CI run for `cargo test` should not cancel runs for other platforms.

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#142]
In recent PRs, CI runs for ubuntu-stable have failed. This causes the mac and ubuntu-nightly runs to be cancelled..

If all runs continue in spite of a failure, we can more easily spot platform / version specific bugs. 

For example, chuffed builds on mac but not some linuxes.  Spotting this kind of issue is only possible if all the CI runs execute, regardless of previous failures.

**Comment by ozgurakgun** [comment]
how is this configured on github actions? I guess one way would be to let the scripts continue (report success) even when builds fail. but that's not ideal.

**Comment by niklasdewally** [comment]
> how is this configured on github actions? I guess one way would be to let the scripts continue (report success) even when builds fail. but that's not ideal.

The issue is the matrix configuration I think - if one matrix permutation fails, the others never run.

Seems to be an easy fix according to the docs: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures

**Comment by ChrisJefferson** [comment]
I think this can be closed now?
