### ISSUE TITLE
Example Rules to Solve a Problem for Minion

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#145]
To show that our rule definition and AST data structures are complete and correct, we should define a few example rules and manually chain these together to solve the below problem  with Minion.

Knowing that rules work manually will also help the testing and debugging of the in-progress rule rewriting system.

* AST objects and API functions should be added as needed.

* To test the registry system, these rules should be added via the macro. Then, they should be retrieved and applied from the registry. Although not a realistic use case, for manual testing, it would be ok to just iterate over the registry, checking the name until it matches a hard coded string. 

* The input model should be read from conjure ast-json as currently happens in `main()`.

* The rule applied at each step and its result should be printed.

* The *raw* solutions from Minion should be printed (we are not worried about translating solutions back to the high level model yet).

**Comment by ozgurakgun** [comment]
Well, not XYZ but something more challenging here.

```
find a : int(1..3)
find b : set of int(1..3)

such that a in b, |b| >= 2
```

Running `conjure solve ab.essence -v` will show you a series of transformations until we reach E'. I can tell you more about each 

Happy to continue discussing this on Friday.

**Comment by ozgurakgun** [comment]
Extracting the important parts of the output of that Conjure command.

Note that you can also add `-ai` to get it to stop before every rule application. So: `conjure solve ab.essence -v -ai`

```
set-in{Occurrence}: Vertical rule for set-in, Occurrence representation
a in b ~~> b_Occurrence[a]

--

set-card: Horizontal rule for set cardinality.
|b| ~~> sum([1 | q2 <- b])

--

set-comprehension{Occurrence}: Vertical rule for set-comprehension, Occurrence representation
[1 | q2 <- b] ~~> [1 | q2 : int(1..3), b_Occurrence[q2]]

--

inline-conditions: Inlining conditions, inside sum
[1 | q2 : int(1..3), b_Occurrence[q2]]
~~>
[toInt(b_Occurrence[q2]) * catchUndef(1, 0) | q2 : int(1..3)]

--

full-evaluate: Full evaluator
catchUndef(1, 0) ~~> 1

--

partial-evaluate: Partial evaluator
toInt(b_Occurrence[q2]) * 1 ~~> toInt(b_Occurrence[q2])

```

**Comment by ozgurakgun** [comment]
Commenting one more time (using separate comments to make separate points)

Some of what's here is not needed for this example. Simplifying manually to:

```
set-in{Occurrence}: Vertical rule for set-in, Occurrence representation
a in b ~~> b_Occurrence[a]

--

set-card: Horizontal rule for set cardinality.
|b| ~~> sum([1 | q2 <- b])

--

set-comprehension{Occurrence}: Vertical rule for set-comprehension, Occurrence representation
[1 | q2 <- b] ~~> [1 | q2 : int(1..3), b_Occurrence[q2]]

--

inline-conditions: Inlining conditions, inside sum
[1 | q2 : int(1..3), b_Occurrence[q2]]
~~>
[toInt(b_Occurrence[q2]) | q2 : int(1..3)]

```

basically by removing catchUndef (don't worry about this for now!) and removing the partial evaluator that's not needed any more.

So it's 4 rules really until we get to E'.

**Comment by niklasdewally** [comment]
> Well, not XYZ but something more challenging here.

I missed when the problem was actually defined (or wasn't listening). Edited!

**Comment by niklasdewally** [comment]
Doing XYZ first is still probably a good idea!

**Comment by lixitrixi** [comment]
I think I will approach this using the XYZ problem, as the problem discussed today would require adding new expression variants and corresponding support for rewriting to Minion.
