### ISSUE TITLE
Better handling of errors produced by solver adapters

### ISSUE THREAD

**Issue by gskorokhod** [conjure-cp/conjure-oxide#151]
Currently, conversion from a conjure `Model` to solver-specific models is done via the FromConjure trait, specifically the function:

```rust
from_conjure(conjure_model: ConjureModel) -> Result<Self, SolverError>
```

The `SolverError` enum is supposed to represent the solver adapter that caused the error, as well as the type of the error and the error message:

```rust
#[derive(Error, Debug)]
pub enum SolverError {
    #[error("not supported in solver `{0}`: `{1}`.")]
    NotSupported(Solver, String),

    #[error("invalid instance for solver `{0}`:`{1}`")]
    InvalidInstance(Solver, String),

    #[error(transparent)]
    Other(#[from] anyhow::Error),
}
```

Currently, the following errors are supported:

- `NotImplemented` (solver adapter does not support a particular essence feature)

- `InvalidInstance` (it's not obvious what this is meant to represent and no one seems to know)

- `Other` 

I think this is not very descriptive and we may want to add more error options and rename the existing ones to make them more self-explanatory, + document the SolverError struct

**Comment by gskorokhod** [comment]
- "Not implemented yet" vs "not supported by this solver in general"
-

**Comment by niklasdewally** [comment]
@gskorokhod you might find my writeup of errors here helpful: 
https://github.com/conjure-cp/conjure-oxide/issues/86

**Comment by niklasdewally** [comment]
Will be done as part of #168.
