### ISSUE TITLE
CI checks to post comments on PRs

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#160]
Where sensible, CI checks should post a summary comment to the PR.

For example: Change in code/doc coverage percentages & a link to the generated html files.

**Comment by niklasdewally** [comment]
Maybe trigger this when:
* Move from draft to ready
* When a review is requested/re-requested.

**Comment by niklasdewally** [comment]
having a yaml day and I wrote the original coverage so i'll take this.

(note to self) we use lcov so can just do this https://github.com/marketplace/actions/code-coverage-comments

**Comment by niklasdewally** [comment]
or https://github.com/irongut/CodeCoverageSummary, seems better.

**Comment by niklasdewally** [comment]
While I'm here  I should probably also do doc coverage diffs:
https://github.com/marketplace/actions/rustdoc-coverage
