### ISSUE TITLE
Test the CNF conversion rules on actual models

### ISSUE THREAD

**Issue by gskorokhod** [conjure-cp/conjure-oxide#163]
Now that a set of rules for simplifying logical expressions has been merged, we need to test them on actual Essence problems to see if there is any problems

**Comment by niklasdewally** [comment]
@gskorokhod is this done?

**Comment by gskorokhod** [comment]
> @gskorokhod is this done?

No

We only have rewrite tests and only for extremely basic cases (e.g. double not)

I meant to add some more this week!

**Comment by gskorokhod** [comment]
> > @gskorokhod is this done?
> 
> No
> 
> We only have rewrite tests and only for extremely basic cases (e.g. double not)
> 
> I meant to add some more this week!

Correction: *had* rewrite tests. They seem to be .disabled now. If Minion supports logical expressions now I will add them back!

**Comment by niklasdewally** [comment]
> Correction: _had_ rewrite tests. They seem to be .disabled now. If Minion supports logical expressions now I will add them back!

Basically yes, but you might need to add type them out in minion_rs:run.rs and in the solver adaptor.

**Comment by niklasdewally** [comment]
minion_rs supports anything that doesn't take in a  tuple table / short-tuple table.

**Comment by ozgurakgun** [comment]
I'll just close this one, it's a bit too generic.
