### ISSUE TITLE
[Discussion] Support conditional rule selection and priority

### ISSUE THREAD

**Issue by lixitrixi** [conjure-cp/conjure-oxide#165]
### Conditional rule selection
As we expand to support reduction to CNF for SAT solvers, we must be able to block certain rules from being used on the model.

For example, the `sum_eq_to_sumeq` which turns `Eq(Sum(arr), _)` into `SumEq(arr, _)`, should not be applied when reducing to CNF, as this is a one-way conversion (for now at least).

### Rule priority
As mentioned by @ozgurakgun in our meetings, we also have to be able to support levels of priority for rules. For example, evaluating sums of constants should be done as early as possible before the expression can be further reduced.

**Comment by niklasdewally** [comment]
This is popping up alot now as something that needs doing (#220 #221 #193) :)

One random idea i've just had for an initial implementation is to just pass the global configs object in as an argument / fetch it from the global static place it lives, and just "selectively apply rules" by looking at the config and returning "not applicable" if its not got the values the rule wants.

**Comment by gskorokhod** [comment]
@lixitrixi @niklasdewally do we still need this, or has it been solved by solver feature flags & the RuleSets PR?

**Comment by niklasdewally** [comment]
@gskorokhod @lixitrixi I disagree that this is solved - but this basically is now a duplicate of #221
