### ISSUE TITLE
A Better Solver Interface

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#168]
This issue discusses areas of improvement to the "solver adaptor interface", and how we interact with solvers more generally. Now that we are tying together, we have begun to notice flaws in our current setup.

## Current Work

Currently, the `FromConjureModel` trait converts a Conjure model to the native data structure of the solver. 
Then, we use the solver crate itself to run it, and collect results. A callback is used to collect results, but this is done using the solver crate's API and differs from solver to solver.

### Example

```rust
fn callback(solution: HashMap<minion_rs::ast::VarName, minion_rs::ast::Constant>) -> bool {
      println!("Solution: {:?}", solution);
      false
  }

// ...

let minion_model = conjure_oxide::solvers::minion::MinionModel::from_conjure(model).unwrap();
minion_rs::run_minion(minion_model, callback).unwrap();
```
(from https://github.com/conjure-cp/conjure-oxide/blob/eaf4f37a8994e7e7f1f33748780d874a62bc4e6d/conjure_oxide/tests/rewrite_tests.rs)

## Related Issues / Existing Work

* #86 
* #151 
* #139 

## Problems and open questions

* **Errors:** How can solvers define and propagate solver-errors upwards? Also, what "default errors" do we want? As discussed in #151, the current names are confusing...

*  **Conditional Compilation:** one should be able to remove solvers through conditional compilation, for example if a solver is not supported on a specific platform, or introduces a breaking change. 

* **Consistent solving interface:** We want to use the same interfaces for calling a solver between solvers. Currently, we use the methods given by `minion_rs` / `kissat_rs`. We want to be able to do something like `solver.solve()` and not care what solver we are actually using.

* **Consistent solutions returning:** We should be able to get solutions from a solver without knowing what solver it is, and results should be returned in conjure_oxide ast types (although still in a primitive low level form). Optionally, we could make higher-level constructs over this, like making the solutions an iterator, or user defined callbacks. 

---

Would appreciate comments, ideas, and things that have confused/annoyed you about the current setup: @gskorokhod @ozgurakgun @lixitrixi @Kieranoski702.

**Comment by niklasdewally** [comment]
I have lots of ideas on how to mangle this into the type system, but if anyone else wants to take this, feel free :)

**Comment by niklasdewally** [comment]
Have lots of ideas for this, and I wrote the last version, so assigned it to myself but happy to give it away if someone else wants it.

**Comment by niklasdewally** [comment]
Also: some solver stuff is in conjure_core, and some is in conjure_oxide - idk why.

**Comment by ChrisJefferson** [comment]
One thing I wanted to mention (as I sometimes see it not well supported).

When a solver is given a time limit, we need to be clear if we got all the solutions, or it stopped before timing out.

I don't know if time limit expiring should be counted as an error. It certainly feels like a different type of error than a modelling issue.

**Comment by niklasdewally** [comment]
> One thing I wanted to mention (as I sometimes see it not well supported).
> 
> When a solver is given a time limit, we need to be clear if we got all the solutions, or it stopped before timing out.
> 
> I don't know if time limit expiring should be counted as an error. It certainly feels like a different type of error than a modelling issue.

I think "timedout" could be a separate state in this state machine. The question then becomes how do we allow solvers to optionally use it.

 Another state that I thought we might use at some point is "has a solution" - which gives us a single solution and a continue method. Again, the issue is how to let the underlying solvers choose the state they want to go into.

**Comment by niklasdewally** [comment]
Would this work to capture the idea of "solving can either go to a set of full solutions, a partial set of solutions, a timeout, a crash, ..."

```rust
pub trait SolverAdaptor {
    type SolverModel;
    type Solutions;
    fn run_solver(model: Self::SolverModel) -> Result<(State,Self::Solutions)>;
    fn init_solver() {} // optional
    // ...
}
```

**Comment by ChrisJefferson** [comment]
I would recommend using a callback style as default for solutions, but can return a list of solutions. It is very, very common to have problems where the set of solutions is more than can reasonably fit in memory -- minion can easily knock out 100,000 solutions a second, which can easily fill half a gig a second, if you have the memory bandwidth.

In such situations, you usually either want to just count the solutions, or sometimes gather some property about each solution as they stream past (which in the past I used to do by hacking minion, so it will be nice to have a better API!)

**Comment by niklasdewally** [comment]
**Some additional requirements (from yesterday's meeting):**

* A stats object should be accessible through the interface when a model is solved. This should have shared fields between all solvers, as well as solver specific stats.

* The interface should use closures not function pointers for the "solution returning" callback - this will make getting solutions out easier!
