### ISSUE TITLE
Constant expression evaluator

### ISSUE THREAD

**Issue by lixitrixi** [conjure-cp/conjure-oxide#169]
As discussed in today's meeting, we will require a way to reduce fully constant expressions to a single constant. @ozgurakgun  proposed making this process separate from the normal expression reduction as the functions can be used elsewhere, and assuming expressions are constants is faster than the normal method.

I would appreciate some more detail on the implementation, although I understand the concept. What I understand is that we can make one large function which accepts an expression of constants and attempts to simplify it. We will then be able to call it from a rule.

**Comment by lixitrixi** [comment]
It seems to me that this function would operate on `Expression`s and we have to unwrap them anyways even when dealing with no variable references (or could we cast them somehow?). As a result it seems more appropriate to use the normal reduction system, albeit with higher priorities for evaluation rules.

If needed by themselves these rules (and by extension their functions alone) can be filtered out from the rule registry based on their priority class or some other metadata we assign them. To me it just seems cleaner to have all of the rewriting happen in a single process which we can otherwise optimize and tweak, although I understand the want for a separate stage which makes a very fundamental set of changes.

**Comment by niklasdewally** [comment]
@lixitrixi Not sure if I fully grasp this in general, but would a big part of this be determining if an expression tree has a bottom layer of just constants, as opposed to other dtypes? 

I remember Oz mentioning refactoring out Constants from the Expression tree in the meeting - was that related to this?
Currently we have:
```rust
enum Expression {
   ConstantInt(...),
   ConstantBool(...),
   //...
}
```

Using rust generics we could instead go towards something like:

```rust
enum Expression {
   Constant(Constant<T: Dtype>),
  //....
}

struct Constant<T: Dtype>;

trait Dtype {}
impl Dtype for Int {}
impl Dtype for Bool {}

fn add_constants(a: Constant<Int>, b: Constant<Int>) {

}
```

The above is illustrative only and not quite right, as it gives us no type information at runtime (which we need), but I agree that having "Constant" be a single variant of expression would be good?


The "go to bottom layer and see if we have constants or not" bit sounds like a macro or a use a lens thing to me, and having the single constant (as Oz suggested) would make that easier and more maintainable.

**Comment by ChrisJefferson** [comment]
One thing which may be worth considering ( @ozgurakgun may have an opinion!) would be to have some easy way of substituting in values for all variables, then constant evaluate to get if a model is solvable. I mention this as I imagine the code will be similar.

This would also be very useful for checking solutions returned from solvers are correct, which picks up bugs in both refinement rules and solvers (finding bugs in solvers is more common than you might expect!)

**Comment by ozgurakgun** [comment]
Yep, this is exactly what we are thinking of @ChrisJefferson. We want a full evaluator that can go from Expression -> Result<Constant> that can be used in a bunch of contexts. Separating Constant from Expression is a part of this as well.
