### ISSUE TITLE
[Discussion] alternative AST structure

### ISSUE THREAD

**Issue by lixitrixi** [conjure-cp/conjure-oxide#173]
I mentioned this idea in a previous meeting but didn't fully expand on it. I'm not fully sure it's the way to go either, but I've been noticing it's rather tricky to expand our functionality with changes to the AST (especially as I'm working on reducing to constants).

I propose a different AST structure similar to the following:

```rust
enum Constant {
  Int(i32),
  Bool(bool),
}

enum Expression {
  Constant(Constant),
  // ...
  UnaryOp(UnaryOp, Expression),
  BinaryOp(BinaryOp, Expression, Expression),
  VecOp(VecOp, Vec<Expression>),
}

trait UnaryOp {}
trait BinaryOp {}
trait VecOp {}
```

This is only a rough sketch, but it could vastly cut down on the number of `match` branches we need.

We could also encode the operation directly into the type:
```rust
trait UnaryOp {
  fn apply(c: &Constant) -> Constant;
}

struct Not {}
impl UnaryOp for Not {
  fn apply(c: &Constant) -> Option<Constant> {
    match c {
      Bool(b) -> Some(!b),
      _ -> None,
    }
  }
}
```
...which could let us do funky things and abstractify typechecking nicely.

**Comment by lixitrixi** [comment]
@ozgurakgun @niklasdewally I would love to hear your feedback; I understand that conjure doesn't do this?

**Comment by lixitrixi** [comment]
We could of course also make the Operations an `enum`. That could look something like this:

```rust
enum UnaryOp {
  Not,
}

impl UnaryOp {
  fn apply(s: &Self, c: &Constant) -> Option<Constant> {
    match s {
      Not -> {
        // as above
      }
    }
  }
}
```

**Comment by ozgurakgun** [comment]
I suggest we keep the current data type and implement full eval for now. 

Briefly: All in all, this won't reduce the number of match clauses, but will just move them around. It might still be worth doing, but we should discuss next time.

**Comment by ozgurakgun** [comment]
Also: what you suggest sounds like a halfway house between one big expression type that has many constructors (what we have now) and an expression trait together with several data types per kind of expression (this was also suggested during our last meeting).

**Comment by niklasdewally** [comment]
I agree that this is an issue, but i'm not sure splitting the AST up like this is the best way. In particular, how do we add  expressions that take a reference and a constant, or a reference and two seperate lists of constraints and so on - I think there will be a lot of exceptions to these rules.

From a quick glance of the Minion source, we have things of the form:

```
read_list,read_tuples
read_list, read_constant
read_constant_list, read_list, read_var
read_constraint_list
```

and so on. These won't fit neatly into these catagories.

**Comment by niklasdewally** [comment]
@lixitrixi if the issue is "we want to enter all sub expressions"/ knowing where the nested expression types are/arn't, that would be a good use case for macros.

Using syn's [1] [ItemEnum](https://docs.rs/syn/latest/syn/struct.ItemEnum.html), you could very easily generate a function that matches all cases of the ast, and does stuff with the ones that have fields of type  Expression. Or even that have fields of type expression that are of some variant T.

6. 1: syn provides a Rust AST for proc macro programming.

**Comment by niklasdewally** [comment]
An idea: we should have a function that just performs a "map" on all sub-expressions using a user-defined function. I think that could be useful in a lot of places.

I.e.

it generates a big match:

```
Eq(a,b)   => (
Neq(a,b),

```

**Comment by niklasdewally** [comment]
An example map function to evaluate references to a value:
```rust
fn ref_to_const(e:Expression,a:Name,b:Constant) -> Expression {
   match e {
     Ref(a) => return Constant(b);
     _ => return e;
  }
}
```

**Comment by niklasdewally** [comment]
> and an expression trait together with several data types per kind of expression (this was also suggested during our last meeting).


For clarity, I am in this camp - I think we could push a bit more onto the Rust type system, instead of doing our own with lots of matches. However, I do see that this could limit our typing later on...

**Comment by lixitrixi** [comment]
> An idea: we should have a function that just performs a "map" on all sub-expressions using a user-defined function. I think that could be useful in a lot of places.

I really like this idea, it would fit nicely as a method of `Expression` too. I know you're not suggesting this as an alternative but the suggested rewrite would tie nicely into this as well:

```rust
fn map_expr(e: Expression, f: fn(Expression) -> Expression) -> Expression {
    match(e) {
        UnaryOp(op, a)  => UnaryOp(op, f(a))
        BinaryOp(op, a, b) => BinaryOp(op, f(a), f(b))
        VecOp(op, exprs) => VecOp(op, exprs.iter().map(|e| => f(e)).collect())
        Constant(i) => Constant(i)
        // ...
    }
}
```
And this would not have to be expanded basically at all.

**Comment by ozgurakgun** [comment]
> An idea: we should have a function that just performs a "map" on all sub-expressions using a user-defined function. I think that could be useful in a lot of places.

this sort of thing reminds me of generic traversal libraries of haskell. uniplate is a good example: https://hackage.haskell.org/package/uniplate

See all methods defined in uniplate here if you want some inspiration: https://hackage.haskell.org/package/uniplate-1.6.13/docs/doc-index.html

There must be similar libraries in rust, but I never looked into them.

**Comment by niklasdewally** [comment]
> > An idea: we should have a function that just performs a "map" on all sub-expressions using a user-defined function. I think that could be useful in a lot of places.
> 
> this sort of thing reminds me of generic traversal libraries of haskell. uniplate is a good example: https://hackage.haskell.org/package/uniplate
> 
> See all methods defined in uniplate here if you want some inspiration: https://hackage.haskell.org/package/uniplate-1.6.13/docs/doc-index.html
> 
> There must be similar libraries in rust, but I never looked into them.

I cant find any, but we could write one!

We just need an additional easy layer of indirection. We just take an enum name in as an argument to the code gen macro!

**Comment by ozgurakgun** [comment]
See https://fitzgeraldnick.com/2017/08/03/scrapmetal.html from a quick google.

**Comment by niklasdewally** [comment]
> See https://fitzgeraldnick.com/2017/08/03/scrapmetal.html from a quick google.

You're better at googling than me it seems :)
Scrap your boilerplate seems great!

**Comment by ozgurakgun** [comment]
oh I just knew the terms I needed to search - the paper is good as well, well worth a read!

**Comment by niklasdewally** [comment]
Another case of Haskell and SPJ being ahead of the curve ...

**Comment by ozgurakgun** [comment]
by 2 decades in this case!

**Comment by niklasdewally** [comment]
@lixitrixi @ozgurakgun 

Me and @gskorokhod   were talking about something unrelated and ended up needing a general abstraction over this elsewhere!

The problem is that of empty Vec<Expression> in constraints.

We have encountered a scenario that needs rules that have And([Or([]]) and reduces it to And([]). (Maybe through an intermediate None type).

**Comment by niklasdewally** [comment]
The generalisation here would be to find all Vec<Expr> types inside variants and run length on them.

**Comment by niklasdewally** [comment]
I suppose actually @Kieranoski702 would've done some of this traversal logic for the rewriting system? We could generalise that to be useful in rules too.

**Comment by niklasdewally** [comment]
The paper: https://www.microsoft.com/en-us/research/wp-content/uploads/2003/01/hmap.pdf

**Comment by ozgurakgun** [comment]
I've been looking at the scrapmetal crate a bit, looks viable.

**Comment by lixitrixi** [comment]
I think I will go ahead and play around with this in another PR once I've done constant rewriting, to see if it actually makes things nicer.

**Comment by ozgurakgun** [comment]
> I've been looking at the scrapmetal crate a bit, looks viable.

So, option (1) scrapmetal

(2) We should also consider: https://crates.io/crates/lens-rs (also see https://www.reddit.com/r/rust/comments/mbisnt/lensrs_guide/)

(3) Was there another library @niklasdewally had found?

(4) implementing our own uniplate style methods

**Comment by niklasdewally** [comment]
> > I've been looking at the scrapmetal crate a bit, looks viable.
> 
> So, option (1) scrapmetal
> 
> (2) We should also consider: https://crates.io/crates/lens-rs (also see https://www.reddit.com/r/rust/comments/mbisnt/lensrs_guide/)
> 
> (3) Was there another lenses/optics library @niklasdewally had found?
> 
> (4) implementing our own uniplate style methods

Nope, it was lens-rs. 

What is the difference between lenses and scrapmetal in this case?

I like scrap your boilerplate; I think that would be useful!

**Comment by ozgurakgun** [comment]
the lens-rs library implements traversals too, so might have comparable functionality

**Comment by niklasdewally** [comment]
> > I've been looking at the scrapmetal crate a bit, looks viable.
> 
> So, option (1) scrapmetal
> 
> (2) We should also consider: https://crates.io/crates/lens-rs (also see https://www.reddit.com/r/rust/comments/mbisnt/lensrs_guide/)
> 
> (3) Was there another lenses/optics library @niklasdewally had found?
> 
> (4) implementing our own uniplate style methods

Scrapmetal will tie us to nightly and an unstable feature (specialisation). I personally don't think this is an issue, but its definitely a consideration.

**Comment by niklasdewally** [comment]
Dtolnay seems to have found a way to do some specialization on stable, if we end up needing to reimplement some of SYP:  https://github.com/dtolnay/case-studies/tree/master/autoref-specialization

**Comment by niklasdewally** [comment]
There also is "Scrap your Zipper"

**Comment by niklasdewally** [comment]
Made a proper issue for traversal (#177) as it keeps coming up!

**Comment by gskorokhod** [comment]
@lixitrixi I actually really like the proposed new AST structure! But also, I see how it could become a problem as we add more different classes of expressions. I think it may still be manageable with proper planning?
I.e at the moment all expression types that we have boil down to unary (Not), binary (Eq and minion flat constraints), ternary (Ineq) and vector (Sum, And, etc). So there isn't a whole lot of special cases to handle.

We definitely should discuss this in more detail at the meeting though! And ultimately Oz would know better as he has done this before.

(Also - the new AST structure isn't mutually exclusive with implementing uniplate, right?)

**Comment by lixitrixi** [comment]
@gskorokhod 

> I.e at the moment all expression types that we have boil down to unary (Not), binary (Eq and minion flat constraints), ternary (Ineq) and vector (Sum, And, etc). So there isn't a whole lot of special cases to handle.

They should currently reduce to the following: Unary, Binary, Ternary, Vector, and Flat. BinaryOp cannot represent Minion flat constraints as they are of type `Vec<Expression>, Expression`, not `Expression, Expression`.

<hr>

> But also, I see how it could become a problem as we add more different classes of expressions. I think it may still be manageable with proper planning though?

I see your point! I tend to think organizing them by signature is more maintainable in the long run than our current structure. When adding a new expression type, chances are we just have to add a single variant to an existing enum for that type, and add rules on how it combines constants, without having to also make traversal rules for it.

If we do have to add a whole new type then all we need to worry about is the specific types of arguments (i.e. `Vec`, `Expression`) and how we loop over them in a structural sense. Once uniplate is added we won't have to worry about this at all, just add a new variant and let the macro deal with how it is structured.

Essentially this will separate traversal from application, and letting uniplate take care of the latter we have to do barely anything to add new types. With our current structure we will always have to worry about AST structure, as it is inherently linked to the actual operators. E.g. to do anything with `Eq`, you must also deal with its two operands.

<hr>

> (Also - the new AST structure isn't mutually exclusive with implementing uniplate, right?)

Definitely not! I think they will complement each other rather well. The refactor will reduce the number of cases uniplate has to write for tree traversal, and uniplate will provide the generic traversal functionality that the refactor lacks out of the box.
