### ISSUE TITLE
[Discussion] Letting rules add to the symbol table and post global constraints

### ISSUE THREAD

**Issue by lixitrixi** [conjure-cp/conjure-oxide#194]
In today's meeting we discussed possible solutions to letting rules which create variables (e.g. direct encoding for SAT) add these variables to the Model's symbol table.

@ozgurakgun mentioned an idea (and stop me if I'm wrong):

- Models contain an optional inner Model, and their own symbol tables are "extensions" of this inner model's symbol table, which is itself a recursive extension of its own inner model. 
- Each rewrite step would add a model around the current one, and rules have read-only access to the current model and return an optional extension to the symbol table, which is then added to the new model link.
- This "chain" of models represents the history of variable assignments; replacing symbols are prioritized, but replaced variables don't actually get overwritten.

I really like this idea, although it seems a bit memory-heavy. I especially like that the chain contains a history of all previous constraint states, which is great for logging (currently we just rely on printing the model at each step, but can't look at the history itself).

I might be extrapolating WAY beyond what was actually said in the meeting, but blame my deeply Rusted brain for that.

**Comment by lixitrixi** [comment]
Regardless of how we approach this, we will need a way to represent specific variable assignments as variables themselves, to be able to share the solution in the language of the original problem.

One way could be extend the `Name` enum to include an expression variant, which allows settings variables to arbitrary expressions, including `Eq`. This seems a bit general but could allow for some funky things down the line?

**Comment by niklasdewally** [comment]
> I really like this idea, although it seems a bit memory-heavy

I don't think we will need to mutate variables very often (horizontal stuff definitely won't need to), so would probably be fine?

> Each rewrite step would add a model around the current one, and rules have read-only access to the current model and return an optional extension to the symbol table, which is then added to the new model link.

It was mentioned in the meeting but I'll repeat it here - the main motivation for a system like this is allowing rewriting with side-effects mid-search (as per #190). We need to know how the model has changed, so we can only send the new bits to the solver.

The process to add the mutated state to the solver would be to look at all the layers of the onion that have been added by the call to rewrite?

**Comment by lixitrixi** [comment]
Just jotting down some notes as I've discussed this in some depth with @niklasdewally. Specifically, how we post global constraints to be added to the top-most layer of the model? And, how does this relate to rules adding to the symbol table?

- Simply passing a mutable model to a rule is a bad idea, as a mistake can have unforseen side-effects. We then need to be careful to pass a fresh copy of the model to every rule when rewriting.
- Additionally, making the passed model be immutable but letting rules return a new model with the global constraints added opens the door to big bad mutability concerns. What if a rule reduces or even deletes the model and the rewriter is still working with a non-empty expression? This introduces a potential source of detachment between model and expression.

My argument is that rules should only be able to make destructive changes on the current expression they are given (i.e. reducing it to a simpler expression), and otherwise only make additive changes to the AST.

- We could use a `Bubble` expression variant based on what @ozgurakgun already does in Conjure: an expression whose purpose is to bring an intermediate global constraint to the top of the AST. These would be evaluated with very high priority. Nik has mentioned that this is basically an `And` constraint, but I find myself disagreeing since `And` brings with it the concept of a type: how do we tell whether something written by the user is to be bubbled up or is simply a type error? A `Bubble` variant makes this distinction clear.
- We could use the "onion" technique to add variables to the model by wrapping it in a symbol table extension:
```rust
struct SymbolOnion(HashMap<Name, DecisionVariable>, Box<SymbolOnion>);
```
The above lets us add an immutable returned symbol table to a recursive structure without the rule having to construct it itself. We can then set the model's field to the new structure.

I might be seriously overthinking this but to my defense it is late and my brain is fried...

**Comment by niklasdewally** [comment]
> What if a rule reduces or even deletes the model and the rewriter is still working with a non-empty expression? This introduces a potential source of detachment between model and expression.


The specific example I gave last night was that if we changed the model globally in a rule, yet the rewriter was focusing on a specific low level expression and expecting that to be rewritten, how will the rewriter update all it's state / it's place in the model/ dirty cleans and so on.

Felix and I seem to agree that part of the  solution is to constrain side effects.

Note that  "how will the rewriter know what's changed" problem is the same problem as  "how will a solver know what's changed" - this is the onion.

**Comment by niklasdewally** [comment]
To put the onion in more standard terminology, I believe we just want to store deltas of a model and previous versions.

**Comment by niklasdewally** [comment]
> how do we tell whether something in the middle of the AST is to be bubbled up or is simply a type error written by the user?

My opinion on this (which I know Felix disagreed with) is that we will be type checking both at the essence input and minion output layer so type checking in the middle may not be needed. It either goes down to minion, is untranslatable and backtracks, or we run out of rules to apply (due to its weird form) and backtrack..

**Comment by niklasdewally** [comment]
> how do we tell whether something in the middle of the AST is to be bubbled up or is simply a type error written by the user?

My opinion on this (which I know Felix disagreed with) is that we will be type checking both at the essence input and minion output layer so type checking in the middle may not be needed. It either goes down to minion, is untranslatable and backtracks, or we run out of rules to apply (due to its weird form) and backtrack..

There's a technical term for this which I forgot (which Oz has used before), but a design desision to make is that whether after each rule application or "rewriting pass" the model has to be valid type checkable essence, or is it only the inputs and outputs that matter?

**Comment by lixitrixi** [comment]
> Whereas I don't care so I would just use ands and if it doesn't bubble up properly it will get caught when we type check the output.

This is a very fair approach, but I feel like there may be a case where using `And`s might turn into an actually incorrect AST (as in, semantically inequivalent to the input model).

**Comment by lixitrixi** [comment]
It will be very difficult to make this work by returning a model with new top-level constraints, as the returned expression tree replaces the model's expression tree, and the data will be overwritten. I will go ahead and attempt this using Bubbles.

**Comment by lixitrixi** [comment]
hmm... actually as long as we return the new top-level constraints separately from the model it should be alright. I should have something to show for this tomorrow afternoon!

**Comment by ozgurakgun** [comment]
A model is a container of vars and cons. The one you return will be
appended to the model you had prior to the rule application. What’s the
issue?

**Comment by ozgurakgun** [comment]
I might be missing something, so genuine question!

**Comment by lixitrixi** [comment]
> A model is a container of vars and cons. The one you return will be
appended to the model you had prior to the rule application. What’s the
issue?

@ozgurakgun if a rule updates the model directly and then a new AST is returned by the rewrite step, the new top-level constraints are overwritten. The top-level constraints must be added after the AST is updated. It's a simple change though, rules just return 2 deltas instead of 1.
