### ISSUE TITLE
CLI Interface for conjure_oxide

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#199]
In order to make conjure-oxide actually usable, it needs to have a CLI interface.

As a starting point, we need

- A `conjure solve` command that takes an Essence file and optionally a params file, produces a solution, and saves it to a file 
- CLI parameters to select the solver 
- CLI patrameters to select a specific frontend
- (MAYBE) flags to enable specific "unstable" features

Wishlist:

- Need to support common UNIX patterns (e.g taking input from stdin, output to stdout)
- Need to stay as close to original conjure as possible
- Need to support a variety of use cases (not just "take a file, get all solutions"

**Comment by gskorokhod** [comment]
Closing #103 as duplicate of this

**Comment by niklasdewally** [comment]
We store global settings in a global context object (https://github.com/conjure-cp/conjure-oxide/blob/main/crates/conjure_core/src/context.rs), as described in #221.

Looking at the UX of Conjure-Oxide, and writing/improving the CLI in general could be a good first issue.

**Comment by niklasdewally** [comment]
This is somewhat ill-defined, so I'll close it for now, and split UX upgrades into individual issues
