### ISSUE TITLE
Cannot cache submodules

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#225]
Action cache keeps failing for #219 due to it having an updated submodule. It reports an error similar to this https://github.com/actions/checkout/discussions/1028 fixable by clearing the cache.

@ozgurakgun what would you think about using sccache (https://github.com/mozilla/sccache/, https://github.com/marketplace/actions/sccache-action) instead? Minion compiles locally already using it, and it works really well for Rust stuff on my local machine. Might work better as well as being easier to maintain / setup.

**Comment by ozgurakgun** [comment]
I don't mind, let's try it!
