### ISSUE TITLE
doc deploy fails

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#237]
last few PR merges had the doc deploy action fail

see https://github.com/conjure-cp/conjure-oxide/actions/runs/8001036695/job/21851472744

**Comment by niklasdewally** [comment]
![ci](https://github.com/conjure-cp/conjure-oxide/assets/44070547/a2f7895e-0274-4742-86ee-e5656625bdcc)

**Comment by niklasdewally** [comment]
Documentation always runs on main right @ozgurakgun ?

Don't see why i split this into two actions - could just be one...
