### ISSUE TITLE
debug / info logging 

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure-oxide#255]
I see people often add, and comment out, various `println!` statements. Might be worth adding logging, controllable by command line or env, and then these logging messages can be left in, not printed by default, but turned on when needed?

**Comment by ChrisJefferson** [comment]
It took me a while to figure out how to dump a log to a file -- you might do better than me, but if not you can look at https://github.com/peal/vole/blob/master/rust/src/bin/vole.rs , where I set up logging for another program.

**Comment by niklasdewally** [comment]
Minus some CLI flags, this is done.
