### ISSUE TITLE
Add --all-solutions flag

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#341]
Savile Row and Conjure only return one solution by default and have an -all-solutions flag to return all solutions.

Conjure Oxide currently only returns all solutions with no way to disable this.

Add a command-line argument, --all-solutions, to Conjure Oxide to toggle between returning one solution and returning all solutions.

**Success criteria:**

When --all-solutions is specified, all solutions to the model are returned by Conjure Oxide. Otherwise, only the first solution is returned.

**Possible steps to completion:**

* Add the command line flag to conjure_oxide/src/main.rs.
* Modify the solution returning logic in `get_minion_solutions` to either return only one solution, or all solutions based on the presence of this command line flag.

**Useful information**

Solution fetching uses the Solver API, documented at https://conjure-cp.github.io/conjure-oxide/docs/conjure_core/solver/index.html. When false is returned instead of true in a solver callback, solver execution is halted.

**Comment by ChrisJefferson** [comment]
This is certainly something long-term I think wants implementing, but I also understand not wanting to fill up an issues list with long-term goals.

Not sure a 30 day close a good idea however, particularly because that will close all the issues over the summer if people aren't working on conjure-oxide!

**Comment by ozgurakgun** [comment]
You are right, maybe we increase it to 90 days or something and also make it ignore a "long term" tag. It's mostly me experimenting with processes.

**Comment by ozgurakgun** [comment]
I think a separate issue that describes the CLI as a project and this being a component of it probably makes more sense?

As a starting point we can try to do something that is compatible (or almost-compatible) with conjure's CLI.
