### ISSUE TITLE
CI: Consistent Caching 

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#36]
Alot of the CI jobs use their own caching mechanism that is hard coded to look at minion, chuffed, minion and chuffed, etc...

I am thinking of a shell script that gets the hash of all submodules from git dynamically, and hashes these, producing a hash that represents all submodule dependencies. 

Using this, all caches can then be converted to the form:

```
nightly-{os}{arch}-gitmodules-{submodules}-cargo-{cargo}
stable-{os}{arch}-gitmodules-{submodules}-cargo-{cargo}
```

This would make CI easier to update if we get new submodules, and allow more cache to be shared between jobs.

Also the paths to cache could be defined in one place (a script or text file in the repo).

(https://stackoverflow.com/questions/12641469/list-submodules-in-a-git-repository)

**Comment by niklasdewally** [comment]
Another issue is that caches on main *should* be accessible to PRs but isnt currently... (they do a full build of everything which is slow).

I think we need to ensure that all caches are present on every commit, at the moment, by the look of the actions panel, not all caches are on main?

I imagine fixing cache to be consistent naming would fix this anyways. 

https://stackoverflow.com/questions/69365200/github-actions-how-to-cache-dependencies-between-workflow-runs-of-different-bra
https://stackoverflow.com/questions/66563672/within-what-limits-github-actions-cache-work

**Comment by ChrisJefferson** [comment]
This might require some more work (particularly with setting up the right compilers), but one option would be https://github.com/marketplace/actions/sccache-action

The idea behind sccache is it hashes files (and all their includes) when they are built, and then later if you build the same thing, it just copies back the result. The advantage is you can just build everything ever time, and it should take very little time, and your cache can't get "out of sync", because if you change any files, they now won't be cached.

I often do this on my own computer, to great success (it speeds up building minion from 3 minutes the first time, to 1.5 seconds the second time). I haven't tried using it on github actions I will admit.

**Comment by ChrisJefferson** [comment]
If you want to investigate this, at the moment minion doesn't support options to set the c++ compiler used, but I'm happy to add one.

**Comment by niklasdewally** [comment]
I think what we are already doing is fine - I just cache the entire of minion build directory on github, then minion uses ccache internally already. This makes rebuilds really fast.

The problem is that each action uses a slightly different cache key that is calculated in different ways. Things would work better if there was one cache for the whole project, to be used across all actions.

I am actually forcing clean builds of minion at the moment on minion update - I imagine this is a holdover from the days where my build.rs were a bit broken and didn't rebuild stuff properly. (I also remember something not rebuilding properly minion side that you fixed?).  I fixed this locally a while back, so could probably fix that here too?

**Comment by niklasdewally** [comment]
Todo on completion:
- [ ] Update wiki
https://github.com/conjure-cp/conjure-oxide/wiki/Github-Actions

**Comment by niklasdewally** [comment]
Also, for CI generally:

- [ ] Conjure Oxide Test and Build
- [ ] Rust docs build and deploy.

**Comment by niklasdewally** [comment]
> I am actually forcing clean builds of minion at the moment on minion update - I imagine this is a holdover from the days where my build.rs were a bit broken and didn't rebuild stuff properly. (I also remember something not rebuilding properly minion side that you fixed?). I fixed this locally a while back, so I could probably remove this from the CI.

To clarify on this, Rust didn't used to regenerate the bindings if I had changed Minion.

**Comment by ChrisJefferson** [comment]
I believe Minion should now correctly rebuild -- but let me know if you ever notice it misbehaving (either building too much, or too little)

**Comment by niklasdewally** [comment]
Possibly use directory listings in GH pages?
https://github.com/marketplace/actions/github-pages-directory-listing

**Comment by niklasdewally** [comment]
- [ ] Probably should fully qualify job names so they should appear good in PRs.

**Comment by niklasdewally** [comment]
https://github.com/glowinthedark/index-html-generator/

**Comment by niklasdewally** [comment]
https://github.com/conjure-cp/conjure-oxide/pull/37
