### ISSUE TITLE
Add a contributing.md file

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#394]
In the light of this week's meeting, I think it's time we write a contributing.md file for the repo. After a quick google, I found this: https://gist.github.com/briandk/3d2e8b3ec8daf5a27a62

We can copy a sensible baseline document like the one above (with attribution of course) and adapt it to our project as needed.

I think a subset of @leiamcalisteryoung, @Soph1514, @YehorBoiar could make a good team for this task?

**Comment by YehorBoiar** [comment]
Looks good to me!

**Comment by ozgurakgun** [comment]
now that we capitilised readme.md (in #395) we should probably call this one CONTRIBUTING.md too :)

**Comment by ozgurakgun** [comment]
Also: the content in the [wiki](https://github.com/conjure-cp/conjure-oxide/wiki) under "Contributor's Guide" should either be incorported or linked to as well. Make sure you read what's there as well as the above template.

**Comment by YehorBoiar** [comment]
I propose @leiamcalisteryoung to open the PR!

**Comment by leiamcalisteryoung** [comment]
Sounds good!
