### ISSUE TITLE
"./conjure_oxide/tests/integration/basic/max/input.essence" doesn't exist anymore

### ISSUE THREAD

**Issue by YehorBoiar** [conjure-cp/conjure-oxide#396]
In conjure_oxide/src/main we reference a test file 
`default_value = "./conjure_oxide/tests/integration/basic/max/input.essence`
But this file doesn't exist. I think, somebody have deleted the max/ folder at some point.

**Comment by niklasdewally** [comment]
I'm in favour of removing the default entirely.

**Comment by YehorBoiar** [comment]
Maybe just comment it out? Sometimes I use it to run examples from the tests folder

**Comment by niklasdewally** [comment]
> Maybe just comment it out? Sometimes I use it to run examples from the tests folder

Try `cargo run -- <args>`? Anything after the -- is interpreted by the program you are running, not cargo.

**Comment by niklasdewally** [comment]
Giving it an essence file as an argument should run it.

**Comment by niklasdewally** [comment]
Another benefit: running cargo run with no args would error and show the --help info.

**Comment by YehorBoiar** [comment]
@niklasdewally Didn't know about that. In such a case, I agree that just removing that line would be a good decision.

**Comment by niklasdewally** [comment]
@ozgurakgun if we get rid of this, would anything break?

**Comment by ozgurakgun** [comment]
don't think so, I agree we should remove the default.
