### ISSUE TITLE
Caching for Github actions

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#4]
I was surprised to see how long the minion tests took. But most of this is the rust dependencies. We cache these in the conjure build, and for rust I just found this: https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/

We should enable similar caching for the minion action (and others in the near future).

**Comment by niklasdewally** [comment]
During development there were some issues that workee/not worked depending on whether one does a clean build or not.


But we could definitely do this for the tests CI - perhaps we could do a quick test and build job using caching, and then full build (without caching) before merge / on marking a PR ready to review?

**Comment by niklasdewally** [comment]
It is probably possible to cache external crates only and not the minion-rs stuff

**Comment by niklasdewally** [comment]
@ozgurakgun is this able to be closed?

**Comment by ozgurakgun** [comment]
Sure. We should keep caching in mind as we add new bindings / for our own rust code as well, of course.

Should we start some developer documentation in the wiki and make notes about these?

**Comment by niklasdewally** [comment]
> Sure. We should keep caching in mind as we add new bindings / for our own rust code as well, of course.
> 
> Should we start some developer documentation in the wiki and make notes about these?

That would be good.

I can't see the wiki on my end so I think you might need to create an "initial commit" on it?

**Comment by niklasdewally** [comment]
> There is a landing page already. Can you not see it on the web?

I can see it now. Thanks :)
