### ISSUE TITLE
Make Reduction new_top, and Model constraints a vector

### ISSUE THREAD

**Issue by YehorBoiar** [conjure-cp/conjure-oxide#421]
We would like to make new_top an attribute in Reduction and constraints in Model a vector. I attempted to implement this in PR #370 but was unsuccessful.

@ozgurakgun, could you clarify the benefits of using vectors for these attributes? I understand that it looks cleaner and might use less space, as an empty vector is smaller than Expression::And(Metadata::new(), Vec::new()). However, are there other reasons I should consider while implementing this change?

**Comment by ozgurakgun** [comment]
I am not sure if it uses less space etc. For me the major benefit is being close to the input model, which in turn means if we pretty print the model it would look closer to what the user wrote.

For reference, this is how model is defined in Conjure: https://github.com/conjure-cp/conjure/blob/4bae499bcc7ec93a69ea0f2ea46078544ddb097c/src/Conjure/Language/Definition.hs#L76

Also see Statement and Expression in that file.

I think we should reproduce this, in addition we will keep context (including symbol table) as well.
