### ISSUE TITLE
Factor --> Term

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#429]
I don't like obsessing over names this much, but the more I think about it the more Factor feels weird to me. It reminds me of an operand to multiply. I checked the dragon book again and this is how they are using it too.

Let's rename it to Term. Any objections, please shout.

**Comment by niklasdewally** [comment]
I prefer `atom`: terms in the lambda calculus, logic, etc. are defined by induction: e.g.`\x -> x + 10` is a term.

The problem with `atom` is that in Prolog `atoms` and variables are different things, but I don't think that many Prolog users will see our internal data structures...

**Comment by niklasdewally** [comment]
However, in Scheme, anything that's not a list (i.e. not a compound term) is an `atom`, which matches our usecase.

**Comment by ozgurakgun** [comment]
I wouldn't veto Atom.
