### ISSUE TITLE
cargo run and cargo test doesn't run

### ISSUE THREAD

**Issue by YehorBoiar** [conjure-cp/conjure-oxide#449]
Hi! I try to run cargo run on the main branch of conjure-oxide, but I get this error

![image](https://github.com/user-attachments/assets/d2c32357-3065-438a-b118-cbc3971761ff)

I run `cargo clean` before it. I even tried to remove the whole repository, then clone it back and run `cargo run` again, but I get the same output. @niklasdewally It says that it's something with minion, did you push any changes about that lately that could have affected the main branch?

**Comment by niklasdewally** [comment]
Have you tried the suggested solution in the error message?

![Screenshot 2024-11-15 at 15 23 58](https://github.com/user-attachments/assets/7ae5c92b-0b37-41ad-a949-b6a12908703d)

**Comment by YehorBoiar** [comment]
Oh yeah, it was an old screenshot. 

![image](https://github.com/user-attachments/assets/b50a3775-68ea-4420-8edd-e7cd5c138721)

here is the current one
