### ISSUE TITLE
[eprime-minion] Implement modulo

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#456]
## Summary

Implement modulo operator and convert it to Minion. As with all other Minion rules, constraints targeting mod specifically should be provided in `minion_constraints`. These should include tests for neq, negated eq, and nested constraints.

I imagine that this will work similarly to division (#454), and similar test cases could be used.

## Tasks

- [x] Add UnsafeMod, and bubbling rules to convert this to SafeMod.
- [x] Parse UnsafeMod
- [x] Add SafeMod flattening rules

## Questions

* What the undefinedness semantics of modulo? Are these the same as division? @ozgurakgun

**Comment by ozgurakgun** [comment]
Should be identical to div, yes.

**Comment by niklasdewally** [comment]
Conjure and Savilerow agree on the div tests that these were based on.

**Comment by niklasdewally** [comment]
Ignore the above: they agree with -S0!

Out of curiosity, whats the symmetries that are being eliminated here?

**Comment by ozgurakgun** [comment]
I was about to ask what options you are passing, because Conjure basically just passes these through. Stick to -S0 indeed.

**Comment by ozgurakgun** [comment]
`conjure solve -v` prints the SR command it runs (among other things) which might be useful.

**Comment by niklasdewally** [comment]
```
Model before undef handling:
language ESSENCE' 1.0
find x : int(5..7)
find y : int(0..3)
find z : int(0..4)
such that
((x%((y%z)))!=3)
Rule:savilerow.TransformMakeSafe
Model has changed. Model after rule application:
language ESSENCE' 1.0
find x : int(5..7)
find y : int(0..3)
find z : int(0..4)
such that
((z != 0) /\ ((((y%z)) != 0) /\ ((x%((y%z)))!=3)))
Model after rule application and simplify:
language ESSENCE' 1.0
find x : int(5..7)
find y : int(0..3)
find z : int(0..4)
such that
(z != 0),
((y%z) != 0)
```

The simplification savile row is making here is calculating the domain of neq and seeing that it is trivially true?

**Comment by niklasdewally** [comment]
> don't feel like you have to do this in this PR, in fact you probably shouldn't, but we should first have:
> 
> * an optional type (this already exists)
> * an optional domain
> * an optional category
> 
> in the metadata.
> 
> we would store the int domain for all Atomic entries, and calculate the domain for all composite expressions.
> 
> we can look into how SR calculates bounds to work out the domains. for example for [mod](https://github.com/savilerow/savilerow-main/blob/842ca61aed8a48b3667b23c560c95faff1972600/src/savilerow/expression/SafeMod.java#L67) and [div](https://github.com/savilerow/savilerow-main/blob/842ca61aed8a48b3667b23c560c95faff1972600/src/savilerow/expression/SafeDivide.java#L82).
> 
> once we calculate the domain of both sides of `!=`, a rule (maybe the partial eval) should rewrite that expr to `true`
> 
> note: SR's getBounds returns an IntPair but we should maintain a Domain since we will have more kinds of domains, not just ints.

captured this in #461
