### ISSUE TITLE
ACCEPT flag doesn't change generated-rule-trace

### ISSUE THREAD

**Issue by YehorBoiar** [conjure-cp/conjure-oxide#476]
I think we should rewrite generated-rule-trace values to expected-rule-trace values when passing true in an ACCEPT flag. @Soph1514 @a-nosnitram @ozgurakgun What do you think?

**Comment by ozgurakgun** [comment]
Exactly. The logos could be copying all generated files to expected, so we don't have to handle each specific case separately.

**Comment by a-nosnitram** [comment]
good idea. on it

**Comment by niklasdewally** [comment]
Closed by #478
