### ISSUE TITLE
CI / Pages: Whole site directory listing

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#52]
Have a directory index for the top level of the site.

Should be similar steps to what we do in code-coverage-deploy.yml, and auto update on change to the root folder of the gh-pages branch

**Comment by niklasdewally** [comment]
@gskorokhod Did you do this in a PR?

**Comment by gskorokhod** [comment]
> @gskorokhod Did you do this in a PR iirc? (close this if so).

We don't have a top level directory listing, we have a static page with links
