### ISSUE TITLE
Chuffed: MacOS CI Build fails

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#66]
At some point today, MacOS CI for Chuffed started failing due to rustc segfaulting.

See https://github.com/conjure-cp/conjure-oxide/actions/runs/6853763458/job/18635293153

**Comment by niklasdewally** [comment]
cc @Kieranoski702 @ChrisJefferson

**Comment by ChrisJefferson** [comment]
Can anyone with a Mac replicate this? If so it might be worth reporting to Rust. Also, it will make debugging much easier!

**Comment by ChrisJefferson** [comment]
We should actually report it anyway, it tells us to in the log. Congrats on finding our first compiler bug!

**Comment by niklasdewally** [comment]
> Can anyone with a Mac replicate this? If so it might be worth reporting to Rust. Also, it will make debugging much easier!
> 
> 

@lixitrixi you run intel right? Could you upgrade rust to latest stable and try this out?

**Comment by niklasdewally** [comment]
I see that it passes in another PR...
https://github.com/conjure-cp/conjure-oxide/actions/runs/6863008776/job/18661892932?pr=32

By the looks of it, Bison and Flex are missing? Are these required to build Chuffed, or optional @Kieranoski702 .

**Comment by ChrisJefferson** [comment]
These kinds of crashes do tend to appear and disappear, it could be related to slightly different versions of mac os x, or libraries.

If noone can replicate locally, my reccomendation is to disable the test on mac for a few weeks and see if it gets fixed. Debugging crashes that only occur on github actions is, I can tell you from experience, just the worst.
