### ISSUE TITLE
Clippy Lints

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#67]
Might be a good idea to have some clippy lints, as CI and / or in the .vscode/settings / rust config somewhere.

See: 
https://doc.rust-lang.org/stable/clippy/usage.html

I am going to add some lints locally on my machine so I don't forget to remove unwrap(), etc - would this be a good thing to put into the repo as well? We could do them for the whole project, or on a crate by crate basis.

**Comment by ozgurakgun** [comment]
I am happy to have these in the repo. We will have to reach a consensus regarding what the set of hints should be, but that doesn't sound too hard.

**Comment by niklasdewally** [comment]
> We will have to reach a consensus regarding what the set of hints should be, but that doesn't sound too hard.

I am thinking if we define a minimal set now, and incrementally add them as problems are found.

Unlike other linters, clippy explicitly encourages the use of #[allow], so adding some more opinionated / niche lints should be fine.

**Comment by niklasdewally** [comment]
Heres the complete list: https://rust-lang.github.io/rust-clippy/rust-1.73.0/index.html
