### ISSUE TITLE
Error binding chuffed when using std::ostream in wrapper.cpp

### ISSUE THREAD

**Issue by Kieranoski702** [conjure-cp/conjure-oxide#70]
I've been trying to create the XYZ problem in my `wrapper.cpp` file to get a better understanding of what functions need to be extracted and wrapped. My current implementation is on my own fork [Here](https://github.com/Kieranoski702/conjure-oxide/tree/main). I currently get a build error at the binding stage that look something like this:

```
error[E0412]: cannot find type `_CharT` in this scope
    --> /home/kieranoski/conjure-oxide/target/debug/build/chuffed_rs-06d3c3e0e6223ba0/out/chuffed_bindings.rs:2125:39
     |
2125 |     pub _M_os: *mut std_basic_ostream<_CharT>,
     |                                       ^^^^^^ not found in this scope
     |
help: you might be missing a type parameter
     |
2123 | pub struct std_basic_ostream_sentry<_CharT> {
```

I believe this comes from the use of std::ostream in the print statement in the XYZProblem class. This is the way that Chuffed gives as the proper way to print results but it seems to cause problems with the bindings and I'm not quite sure what is going wrong. If anyone knows how to fix this or a better way to output the results then please let me know!

**Comment by ChrisJefferson** [comment]
The basic problem is std::ostream is too big and complicated for binding, but it becomes part of the API when you return it from new_problem.

This patch seems to fix it, basically we return, and pass back in, void*, which stops bindgen trying to unstand the internals of Problem. I havent tested this beyond checking it builds.

```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: solvers/chuffed/wrapper.cpp
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ solvers/chuffed/wrapper.cpp:100 @ public:
};

// Create new problem
void *new_problem() { return new XYZProblem(3); }

// Solve problem
void solve(void *p) { engine.solve((XYZProblem *)p); }
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: solvers/chuffed/wrapper.h
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ solvers/chuffed/wrapper.h:31 @ void destroy_vec_intvar(vec<IntVar *> *v);
void branch_IntVar(vec<IntVar *> *x, VarBranch var_branch,
                   ValBranch val_branch);

void *new_problem();
void solve(void *p);
```

**Comment by Kieranoski702** [comment]
> The basic problem is std::ostream is too big and complicated for binding, but it becomes part of the API when you return it from new_problem.
> 
> This patch seems to fix it, basically we return, and pass back in, void*, which stops bindgen trying to unstand the internals of Problem. I havent tested this beyond checking it builds.
> 
> ```
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> modified: solvers/chuffed/wrapper.cpp
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> @ solvers/chuffed/wrapper.cpp:100 @ public:
> };
> 
> // Create new problem
> void *new_problem() { return new XYZProblem(3); }
> 
> // Solve problem
> void solve(void *p) { engine.solve((XYZProblem *)p); }
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> modified: solvers/chuffed/wrapper.h
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> @ solvers/chuffed/wrapper.h:31 @ void destroy_vec_intvar(vec<IntVar *> *v);
> void branch_IntVar(vec<IntVar *> *x, VarBranch var_branch,
>                    ValBranch val_branch);
> 
> void *new_problem();
> void solve(void *p);
> ```

Thanks! This solves the build issue but running it causes a, fairly expected, seg fault. I'll try to do some debugging to figure out where it crashes and what's going wrong. Thanks again for the help

**Comment by ChrisJefferson** [comment]
At a quick glance (not tested, I might be wrong), you don't create `sum` like x,y and z.
