### ISSUE TITLE
Setup Parsing Integration Test Runner

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#72]
As per #32 and discussed offline.

We aim to write integration tests that read in essence files from a directory tree, convert them to JSON, runs them through the JSON parser (being written in #32), and compares the generated conjure-oxide::Model to a given expected value.

This comparison will be done by serialising the rust model to json, and comparing against a given expected json output.
 
Future work will add more steps to this integration test runner (e.g. model translation) , and allow the selection of which steps to test on a per file basis.

**Comment by niklasdewally** [comment]
@lixitrixi you know more about this - can you describe this and work out how to split this up into multiple PRs?

**Comment by lixitrixi** [comment]
@ozgurakgun Would it be wise to both:

1. Serialize the Oxide Model and compare against the expected file content
2. Deserialize the expected file content into a model and compare against the Oxide Model

This way we're ensuring that serialization works as well; not sure if this was already agreed upon.

**Comment by ozgurakgun** [comment]
Yes it's a good idea to do both but I don't want to delay the merging of this PR. Let's do 1 only first?

**Comment by lixitrixi** [comment]
If it makes it any more complicated to do both I will leave it, but it should be as simple as deriving Deserialize for the model.
