### ISSUE TITLE
Unified Error Handling 

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#86]
Related to #75 #85 #83 #32.

Once the above PRs are merged, we should combine error types such that everything bubbles up to the top level nicely. At the moment, there is no common error handling approach on main, so PRs have nothing to base proper error handling off of.

I'm thinking a bottom up approach. Each layer uses error types that are sensible to them.
Then, consumers of the layers have their own types, that use #[from]  / impl From and Error to create sensible abstractions for that layer.
E.g. the big error enums in #32 and #85 .

I am not quite sure how to structure this, but I have been using the following crates for now:

https://docs.rs/thiserror/latest/thiserror/
https://docs.rs/anyhow/latest/anyhow/

**The main motivation (for me) is to avoid unwrap(), expects(), todo!(), panic!(), .... and replace these with functions that can bubble up errors to the top of the program with ?, maintaining backtraces.**

We could also, in top layers, use anyhow::Error and anyhow::Result to have polymorphic errors.

## `this_error`
Using this_error crate, we can easily create "layers of errors", which properly trace origin and store backtraces, etc: 

```
#[derive(Error, Debug)]
pub enum DataStoreError {
    #[error("data store disconnected")]
    Disconnect(#[from] io::Error),
    #[error("the data for key `{0}` is not available")]
    Redaction(String),
    #[error("invalid header (expected {expected:?}, found {found:?})")]
    InvalidHeader {
        expected: String,
        found: String,
    },
    #[error("unknown data store error")]
    Unknown,
}
```

Error types can support misc error types using transparent errors, which pass their messages through unmodified:
```
#[derive(Error, Debug)]
pub enum MyError {
    ...

    #[error(transparent)]
    Other(#[from] anyhow::Error),  // source and Display delegate to anyhow::Error
}
```

To use this in a function that returns `Result<(),MyError>`:

```
let c_str = CString::new(var_name.clone()).map_err(|e| anyhow!(e))?;
```

This will give a `MyError::Other()` with the source being CString's `NilError`.

Instances where we want to throw a string as an error, we can use `anyhow!`:

```
return Err(anyhow!("This is an error"));
```

**Comment by niklasdewally** [comment]
Ping: @lixitrixi

**Comment by niklasdewally** [comment]
As main can return result, we can maybe do:

```
fn main() -> anyhow::Result<()> {

....

}
```

**Comment by ChrisJefferson** [comment]
I approve of these crates, and this general design. Also for now errors just leaving main seems reasonable, we can make something nicer later.

My only comment is that when interfacing with solvers, it is better to panic if the alternative is leaving the solver in a broken / inconsistent state, as bugs caused by this can be very hard to fix.

Longer term there might either be some way to always "clean" a solver, or mark it is broken (so you throw an error every time someone tries to use it).

Also, it's fine (again my my opinion) to use expect if you can't figure out how to actually make the class fail, which then makes it untestable anyway.

**Comment by niklasdewally** [comment]
> My only comment is that when interfacing with solvers, it is better to panic if the alternative is leaving the solver in a broken / inconsistent state, as bugs caused by this can be very hard to fix.

I agree - atm I have been using lints on expect and unwrap to force me to clean up prototype code and make a conscious decision on how an error should be handed, as opposed to a dogmatic style guide - I make decent use of #[allow(unwrap_used)] when it's appropriate, primarily in the "during solver bits of the minion bindings".

**Comment by niklasdewally** [comment]
Something I did alot was to say todo!() on a match wildcard, when instead we would probably want to throw "not implemented" upwards instead

**Comment by niklasdewally** [comment]
Will need revisiting once we have prototyped further.

**Comment by niklasdewally** [comment]
Now covered by #151 and #168
